// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6UeVBCBvd64cUuN5tbIWGaGs-ZN7Z_A8',
    appId: '1:420839265763:web:57bf94f019214b8ad13cd6',
    messagingSenderId: '420839265763',
    projectId: 'my-ink-project-dbe41',
    authDomain: 'my-ink-project-dbe41.firebaseapp.com',
    storageBucket: 'my-ink-project-dbe41.appspot.com',
    measurementId: 'G-L6NLHB3PDL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgx78lChRGr3MvdUZsG2NHVNyOwk011Po',
    appId: '1:420839265763:android:756a2885511b795ed13cd6',
    messagingSenderId: '420839265763',
    projectId: 'my-ink-project-dbe41',
    storageBucket: 'my-ink-project-dbe41.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWqUtWOUW_zmvfeAf9nwNzL7D_0QjQjL4',
    appId: '1:420839265763:ios:d3b6d2a24b233c82d13cd6',
    messagingSenderId: '420839265763',
    projectId: 'my-ink-project-dbe41',
    storageBucket: 'my-ink-project-dbe41.appspot.com',
    iosBundleId: 'com.example.ink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWqUtWOUW_zmvfeAf9nwNzL7D_0QjQjL4',
    appId: '1:420839265763:ios:9e697a7745e33739d13cd6',
    messagingSenderId: '420839265763',
    projectId: 'my-ink-project-dbe41',
    storageBucket: 'my-ink-project-dbe41.appspot.com',
    iosBundleId: 'com.example.ink.RunnerTests',
  );
}
